name: Deployment

on:
  push:
    branches: [ci/deploy]

jobs:
  build-and-deploy-dev:
    name: Build and deploy on DEV
    runs-on: dev-runner
    timeout-minutes: 30
    env:
      AWS_ACCOUNT_ID: 028828968899

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 028828968899.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: true
          tags: 028828968899.dkr.ecr.eu-central-1.amazonaws.com/mygenassist/attendee:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
